### ISSUE TITLE
Entering a command from console gives an error.

### ISSUE THREAD

**Issue by Repaler** [Livaco/Staff-Restrictor#1]
As the title says, using rcon or console creates an error when doing a command such as 'ulx adduser NAME superadmin'. It complains about there not being a valid team to the player, but of course there wouldn't be, since the console has no team. I fixed it by adding a simple IsPlayer check on line 26 of sv_main.lua. Hope I could provide enough info

**Comment by Livaco** [comment]
Sorry for taking so long to get back to you. I'l look into this tomorrow, thanks for informing me!

**Comment by Livaco** [comment]
Pushed an update that fixes this. Thanks for making an issue!

**Comment by Livaco** [comment]
Closing.
